### PR TITLE
Bring up-to-date and gets specs passing.

### PR DESCRIPTION
**Pull request by jeremywadsack**
- Update `yajl` because of broken "Symbol not found" error
- Add missing #constantize method for PushPop (#2)
- Fix broken reference to rdoc/tasks for latest doc
- Remove redis configuration options that are no longer supported
- Fix resque worker to use new term_child method of signal handling

### CODE REVIEW

**Comment by frausto** [comment]
@jeremywadsack, thanks for the interest in getting this up to date. I'll go ahead and merge it in once the tests are passing on travis for the older versions of ruby, though Im fine with getting rid of the 1.8.7 support. Its obviously been a while since the last update, let me know if you are interested in taking over these projects.

**Comment by jeremywadsack** [comment]
It's odd that 1.9.1 fails in Travis because I fixed that issue [here](https://github.com/keylimetoolbox/resque-remora/commit/b7a99082ca12f2c3e95448b8be8e4e09aeaf2be5#diff-52c976fc38ed2b4e3b1192f8a8e24cffR43). Is that a Travis configuration issue?

1.8.7 is failing because it uses the old `rdoctasks` require file; so I think it's best to remove support for it.

I'm not really sure what to do about this error:

```
The signal QUIT is in use by the JVM and will not work correctly on this platform
The signal USR1 is in use by the JVM and will not work correctly on this platform
```

That's weird that JVM won't pass a unix signal to the process. But I'm unfamiliar with JVM.

Any thoughts on fixing either of those?

**Comment by jeremywadsack** [comment]
FWIW, 1.9.2 is [no longer a supported ruby](https://www.ruby-lang.org/en/news/2014/07/01/eol-for-1-8-7-and-1-9-2/) and also [does not build on OSX 10.10](https://github.com/wayneeseguin/rvm/issues/3099) (so I can't test it locally to identify a fix.)

**Comment by jeremywadsack** [comment]
@frausto I updated the `travis.conf` and removed ruby 1.8, along with 1.9.2. It also doesn't appear to be a [pre-compiled binary on Travis either](http://rubies.travis-ci.org/) so it seems that of the 1.9 branch it's 1.9.3 or nothing. Are you ok with that?

**Comment by jeremywadsack** [comment]
Thanks Nolan. 

As to your question of whether I'm interested in taking ownership, not for this gem. 

I was looking for an auto-scaling solution so was more interested in resque-director. I just needed all this to get it working. However, having dug into that it looks like it would need a complete overhaul for my needs as we run multiple queues (given that it uses a singleton configuration it doesn't work for more than one queue), we run our workers off the app server (so we'd need to use the `no_enqueue_scale` option; but I'd like to figure out a small monitoring daemon that would allow running 0 workers with this option), and we run across multiple servers (but not on Heroku which all the other auto-scaling is built around). If I decided to go the route to get all the working with resque-director as a starting point, then I might be interested in taking that over. But I'd swap out resque-remora for resque-meta so that I would have one less gem to manage. :)

That effort is large and a spike, so no promises that I'll make much progress on it.

**Pull request merged**
